### ISSUE TITLE
where can I download the pretrained model?

### ISSUE THREAD

**Issue by qq237942920** [uber-research/UPSNet#1]
where can I download the pretrained model like “resnet-50-caffe.pth”

**Comment by YuwenXiong** [comment]
Please carefully check README, and make sure you run init.sh first

**Comment by qq237942920** [comment]
thx!

**Comment by JoyHuYY1412** [comment]
> Please carefully check README, and make sure you run init.sh first

Is this pretrained model trained on ImageNet for image classification?  When I run your code, I found the 
`rcnn_accuracy` is already high in the beginning. Does that mean the rcnn head has been trained well?
