### ISSUE TITLE
init_coco.sh bug

### ISSUE THREAD

**Issue by LaoYang1994** [uber-research/UPSNet#10]
It seems that there is a bug in init_coco.sh.
maybe `PYTHONPATH=$(pwd)/lib/dataset_devkit/panopticapi:$PYTHONPATH` should change to
`PYTHONPATH=$(pwd)/lib/dataset_devkit:$PYTHONPATH`

**Comment by YuwenXiong** [comment]
Thanks for pointing out, now it has been fixed.
