### ISSUE TITLE
how can I train from scratch? 

### ISSUE THREAD

**Issue by discretecoder** [uber-research/UPSNet#100]

**Comment by discretecoder** [comment]
I was also wondering if you have tried to train with depth? thanks

**Comment by Hcyang-NULL** [comment]
Just set network.use_pretrained to False in your own yaml file and it will train from scratch. 
![image](https://user-images.githubusercontent.com/46910054/68595881-462b2800-04d5-11ea-8df7-27b921594f3f.png)
you also can modify this configuration in config/config.py (default configurations)
