### ISSUE TITLE
ModuleNotFoundError: No module named 'upsnet.operators.modules.distbatchnorm'

### ISSUE THREAD

**Issue by ParanoidW** [uber-research/UPSNet#12]
Error message:
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 61, in <module>
    from upsnet.models import *
  File "upsnet/../upsnet/models/__init__.py", line 1, in <module>
    from .resnet_upsnet import resnet_50_upsnet, resnet_101_upsnet
  File "upsnet/../upsnet/models/resnet_upsnet.py", line 23, in <module>
    from upsnet.models.fpn import FPN
  File "upsnet/../upsnet/models/fpn.py", line 23, in <module>
    from upsnet.operators.modules.distbatchnorm import BatchNorm2d
ModuleNotFoundError: No module named 'upsnet.operators.modules.distbatchnorm'

**Comment by YuwenXiong** [comment]
Thanks for pointing it out, you can simply comment out all lines which try to import distbatchnorm or pull the latest code.

**Comment by ParanoidW** [comment]
Thanks you. Another question, what should I do if I want to use syncbn?

**Comment by YuwenXiong** [comment]
Currently our syncbn requires horovod, however we still have some issues on it so I didn't release it. Please ignore it at the moment.

**Comment by ParanoidW** [comment]
Does it has a influence on results?

**Comment by PkuRainBow** [comment]
We have tried to run the UPSNet based on the Inplace-ABN with pytorch0.4.1 but find the performance drops.
We apply the Inplace-ABN in both the backbones and the detection head +segmentation head.
It would be great if you could share with us some advice.
