### ISSUE TITLE
Can't generate Panoptic results, only Instance.

### ISSUE THREAD

**Issue by youkibebop** [uber-research/UPSNet#137]
I successfully trained the network, and tested the Instance segmentation results, but the testing stalls at the code for generating the panoptic results. Initially, the error I received was: ModuleNotFoundError: No module named 'panopticapi.utils'. I solved this by using pip to install panopticapi. But now, upsnet_end2end_test.py will not generate the panoptic results.  It appears to be stalling after calling line 308 in upsnet_en2end_test.py: 

test_dataset.evaluate_panoptic 

Please let me know what I can do to fix this. The last two lines of my log file look like this:

2020-10-18 01:04:39,663 | base_dataset.py | line 718: ~~~~ Summary metrics ~~~~
2020-10-18 01:19:14,930 | upsnet_end2end_test.py | line 307: unified pano result:

**Comment by wshilaji** [comment]
Have you solved the problem？I have this problem, too.Can you teach me?
2020-10-18 01:19:14,930  upsnet_end2end_test.py | line 307: unified pano result:

**Comment by wshilaji** [comment]
In addition, do you know how to generate own custom coco format Panoptic segmentation dataset？

**Comment by rlangefe** [comment]
The issues we had with this kind of error involved not running the init.sh script, which should pull that repo into the UPSNet directories and compile things. Also, the coco_init.sh file runs some useful things. We made a similar script built from the first one to initialize things and make sure it edited the pulled files correctly, as well as generate proper data. To the question of how to make this in the proper format, take a look at coco's documentation for the format. We took code from https://patrickwasp.com/create-your-own-coco-style-dataset/ and modified it. Essentially, you have to use his code to generate the instances file by filtering for the isthings items and then generate the other files by modifying the code. If I remember right, you need 3 json files for data and one for classes.
