### ISSUE TITLE
Cannot find reference 'deform_conv_cuda'

### ISSUE THREAD

**Issue by sitingshen** [uber-research/UPSNet#14]
Thanks for your great work.
I followed the installation steps and  the installation was successful,but when i begin to train the model ,it tells me "Cannot find reference 'deform_conv_cuda'",but the file is already exists，i don't how to fix it. Could you help me with this? Thanks.

**Comment by Xiaolongbetter** [comment]
I think you may find the answer here [https://github.com/uber-research/UPSNet/issues/6](url).

**Comment by Xiaolongbetter** [comment]
I think you may find the answer by previous help-seeking question "Question about undefined symbol".

**Comment by sitingshen** [comment]
it works，thank you very much for your answer.

**Comment by StoicGilgamesh** [comment]
Can you please tell me how did you managed to solve it? i am having the same issue

**Comment by sitingshen** [comment]
On this issue, I wrote '-D_GLIBCXX_USE_CXX11_ABI':['0'] to line 51 of this file.[https://github.com/uber-research/UPSNet/blob/master/upsnet/operators/build_deform_conv.py](url) @StoicGilgamesh

**Comment by sitingshen** [comment]
On this issue, I wrote '-D_GLIBCXX_USE_CXX_ABI':['0'] to line 51 of this file.https://github.com/uber-research/UPSNet/blob/master/upsnet/operators/build_deform_conv.py @StoicGilgamesh
