### ISSUE TITLE
How could we get PQ values?

### ISSUE THREAD

**Issue by WenFuLee** [uber-research/UPSNet#18]
No matter I run training or testing script, the metrics all I see are AP or AR. Wondering if we should we calculate PQ values ourselves. Or there is anything I missed? Thanks.

**Comment by Xiaolongbetter** [comment]
When test on cityscapes, I can get PQ values directly. And I could get the panoptic segmentation results like below：
![image](https://user-images.githubusercontent.com/38773847/56257870-42325580-6100-11e9-857b-02bdaf1ff371.png)
I think you should describe the details of the problem you are experiencing more carefully.

**Comment by qq237942920** [comment]
@WenFuLee I meet the same problem as you said, but I just test the cocodataset. Furthermore, I found the another problem is that key "color" is not in `panoptic _coco_categories_stiff.json` after `coco_init.sh` which  seems to cause the problem when we calculate PQ values. When I refer to the `panoptic_api` in official github: [https://github.com/cocodataset/panopticapi/blob/master/panoptic_coco_categories.json](url)
It allocates every categories with different colors, which is different from `panoptic _coco_categories_stiff.json` without the key "color".

**Comment by Xiaolongbetter** [comment]
@qq237942920  For coco dataset，Please pull the latest code ''init_coco.py'' and regenerate panoptic_val2017_stff.json. I think it will be fine.

**Comment by qq237942920** [comment]
@YuwenXiong I think your team completed the work before the update of `panoptic_api`, so when I git clone the updated panoptic_api, you still use it with old version. Actually, there are many issues about `COCO Panoptic data does not have 'color' attribute`  in `panoptic_api`. If I'm wrong about your project, I'm so sorry and looking forward your reply.

**Comment by qq237942920** [comment]
> @qq237942920 For coco dataset，Please pull the latest code ''init_coco.py'' and regenerate panoptic_val2017_stff.json. I think it will be fine.

I tried it again ,but it still tell me the same problem.

**Comment by qq237942920** [comment]
@Xiaolongbetter @YuwenXiong Oh,I found the project had updated 4 hours ago, so I think it fixed the bug about it. I'm so sorry for my problem. Thank you for your patient reply.

**Comment by WenFuLee** [comment]
@Xiaolongbetter I saw your above panoptic segmentation results. Wondering when you got your PQ results, did you experience this issue: https://github.com/uber-research/UPSNet/issues/22. Thanks.

**Comment by WenFuLee** [comment]
This issue was solved after successfully evaluating the test set.
