### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by WenFuLee** [uber-research/UPSNet#20]
(1) After setting vis_mask to true, I got the result below. However, I found all cars are recognized as trains...Wondering if there is something with my training
<img width="1401" alt="Screen Shot 2019-04-16 at 9 48 28 PM" src="https://user-images.githubusercontent.com/34199594/56257314-715dae00-6091-11e9-89e5-6f442ceafbb9.png">

(2) How do we get the result of panoptic segmentation as below, instead of the one above (like instance segmentation)?
<img width="353" alt="Screen Shot 2019-04-16 at 9 51 32 PM" src="https://user-images.githubusercontent.com/34199594/56257492-0660a700-6092-11e9-8a0b-8f41d5210424.png">

**Comment by YuwenXiong** [comment]
If you evaluate PQ successfully you will get those panoptic segmentation output (they are saved automatically to get PQ number).

For vis_mask, sorry that that part of code is outdated and class order is not right, I've updated it, please pull the latest code and you will get right visualization.

**Comment by discretecoder** [comment]
@WenFuLee how did you solve this problem?
