### ISSUE TITLE
 Question about visualization when trying to test COCO dataset(train2014)

### ISSUE THREAD

**Issue by AllenSpurs** [uber-research/UPSNet#21]
Thanks for your great work!
I had trained the model with COCO train2017&val2017, and pulled the latest code, but when I trying to test COCO dataset (train2014) with setting the vis_mask=True, I still only got an instance segmentation like figure.
Is there anything that needs special attention? 
![COCO_train2014_000000000025 jpg](https://user-images.githubusercontent.com/38784792/56272497-622c3e00-612d-11e9-83e4-afe1899957bd.png)

**Comment by qq237942920** [comment]
Do you want to get the panoptic segmentation figure?

**Comment by AllenSpurs** [comment]
> Do you want to get the panoptic segmentation figure?
Yes, that is what I want, I just want to utilize the panoptic segmentation figure to extract some image feature. Need any sepcific setting here?
Thank you.

**Comment by AllenSpurs** [comment]
Yes, that is what I want, I just want to utilize the panoptic segmentation figure to extract some image feature. Need any sepcific setting here?
Thank you.

**Comment by qq237942920** [comment]
No, it will produce the panoptic segmentation figures for you automatically！

**Comment by AllenSpurs** [comment]
So if all goes well, should the panoptic segmentation figures  be in the directory like "UPSNet/output/upsnet/coco/upsnet_resnet50_coco_4gpu/test2015/results/vis"?

**Comment by qq237942920** [comment]
directory like "UPSNet/upsnet/output/upsnet/coco/upsnet_resnet50_coco_4gpu/val2017/results/pans_unified/pan/"

**Comment by AllenSpurs** [comment]
OK, I will set the mask_vis to False and try it again. 
Thank you for your patient reply.
