### ISSUE TITLE
Code not executing

### ISSUE THREAD

**Issue by gupta-abhay** [uber-research/UPSNet#28]
Hi,

After following all the steps mentioned and setting up the environment as python 3.6; pytorch 0.4.1; the code has many bugs making it difficult to reproduce the results. Are there some other changes that need to be done - or do following these steps directly work? I am trying to train the model on COCO using the single GPU config file.

**Comment by YuwenXiong** [comment]
We don't provide 1 gpu config file, I think you might be using the 16gpu config file which requires Horovod. Please modify the 4gpu config by following this: https://github.com/uber-research/UPSNet/issues/9#issuecomment-481302785 if you want to use 1 GPU

**Comment by gupta-abhay** [comment]
After reading the issue - it seems that we need python 3.7 and 3.6 - if so, can you update the README with the same?

**Comment by YuwenXiong** [comment]
I think you misread the issue. And I use python 3.6 and CUDA 9.1.

If the code cannot execute on your side please post essential information/output here.

**Comment by gupta-abhay** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/8841427/56710549-bf5b5d00-66f4-11e9-88ed-cf67a787d953.png">

getting error similar to issue #9 - i have compiled with python 3.6 and cuda 9.1; i have only 1 GPU - did the suggested changes. I am trying to run for COCO dataset.

**Comment by gupta-abhay** [comment]
Got the code working! Thank you for the inputs.

**Comment by Eswar1991** [comment]
> Got the code working! Thank you for the inputs.

Can you suggest the way to solve this bug?? It's really killing us
