### ISSUE TITLE
How to reproduce the result reported in the paper?

### ISSUE THREAD

**Issue by koncle** [uber-research/UPSNet#29]
I have trained the network with the configuration file of upsnet_resnet50_cityscapes_4gpu.yaml and 4 2080Ti gpus. The configuration file is not modified at all.

And after testing the model with test_iteration of 48000, the result shows that mIoU is 75.054%, AP_box is 38.1%, AP_mask is 32.4%, PQ:SQ:RQ is 58.7% : 79.6% : 72.4%. But the result reported in the papr is 75.2%, 39.1%,  33.3%, 59.3% : 79.7% : 73% separately.

Is there any way to achieve the performance reported in the paper?

**Comment by YuwenXiong** [comment]
We noticed that on Cityscapes the result will have ~0.5 point varaiance and our results are obtained in 16 GPU setting so there might be some difference. On COCO the result is more stable. We will release the pretrained model weights that can reproduce the result reported in our paper.

**Comment by koncle** [comment]
Thank you for your reply!
