### ISSUE TITLE
About soft copy or deep copy in init_coco.py

### ISSUE THREAD

**Issue by qq237942920** [uber-research/UPSNet#3]
Thanks for your good project, I have a question about your code. The code in your project you released `pano_json_stff = pano_json.copy()` is dict.copy, which is soft copy in subobject , only deep copy in parent object. It seems to make the categories repeated and wrong in `panoptic_coco_categories_stff.json`. Could you tell me whether the code is correct?

**Comment by YuwenXiong** [comment]
Thanks for point out this issue. You are right, I made this bug when I release the codebase (the annotation files I used were generated long time ago. And I just rewrote the code before I released it and didn't do carefully check.) Thanks again, now the code has been updated and please rerun init_coco.py to generate the new annotation files.

**Comment by qq237942920** [comment]
OK! Thank you for your patient reply and nice work!
