### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LaoYang1994** [uber-research/UPSNet#31]
https://github.com/uber-research/UPSNet/blob/9191a59de894ae95831b622c7d20102db5c93b6f/upsnet/models/resnet_upsnet.py#L287
        cls_idx = roidb['gt_classes']

Line 287 should be: cls_idx = roidb['gt_classes'][gt_inds]

**Comment by YuwenXiong** [comment]
Thanks for pointing it out, this bug will be triggered when `panoptic_box_keep_fraction = 1`, now it has been fixed.
