### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LaoYang1994** [uber-research/UPSNet#33]
https://github.com/uber-research/UPSNet/blob/96b7b5172b7b76446f637f4922b7a2054e46703b/upsnet/models/resnet_upsnet.py#L285

I think it should be
        gt_inds = np.where((roidb['gt_classes'] > 0) & (roidb['is_crowd'] == 0))[0]

But when I modify it like this, another problem occured. I think it's due to the instance that is crowd.

I think in this place, the crowd instance should be added to construct the pan_gt.

**Comment by YuwenXiong** [comment]
Yes you are right, there is a bug here. I think the crowd instance should be filtered and ignore in training. The problem you encountered is because I include crowd annotation in other places. I'm launching a new exp to see whether we should fix it.

**Comment by YuwenXiong** [comment]
My recent results show that there is no performance influence w.r.t this issue. It has been fixed now.
