### ISSUE TITLE
Is the bounding box regression loss different from Mask RCNN? 

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#34]
https://github.com/uber-research/UPSNet/blob/96b7b5172b7b76446f637f4922b7a2054e46703b/upsnet/models/rcnn.py#L179
You code here just use the coordinates to calculate loss, but original bounding box regression in MaskRCNN uses ground truth like this: tx=(Gx−Px)/Pw, ty=(Gy−Py)/Ph, tw=log(Gw/Pw), th=log(Gh/Ph).

Does it matter?

**Comment by YuwenXiong** [comment]
This is regular smooth l1, we calculate regression target here: https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L114

**Comment by JoyHuYY1412** [comment]
> This is regular smooth l1, we calculate regression target here:
> 
> https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L114

Sorry, but I cannot find in your code where you use this function. Could you point out?

**Comment by JoyHuYY1412** [comment]
> > This is regular smooth l1, we calculate regression target here:
> > https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L114
> 
> Sorry, but I cannot find in your code where you use this function. Could you point out?

Oh maybe it is this function,
https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L290

**Comment by JoyHuYY1412** [comment]
> This is regular smooth l1, we calculate regression target here:
> 
> https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L114

Do you mean this one?
https://github.com/uber-research/UPSNet/blob/4da1b65bbd79212ec78f29f359063eb93a8f4ab6/upsnet/bbox/bbox_transform.py#L332
