### ISSUE TITLE
RuntimeWarning: invalid value encountered i$  greater_equal

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#37]
Has anyone encounter this error when running with one GPU?

> upsnet/../upsnet/operators/functions/pyramid_proposal.py:229: RuntimeWarning: invalid value encountered i$  greater_equal
>   keep = np.where((ws >= min_size) & (hs >= min_size))[0]

The whole message is:

> upsnet/../upsnet/operators/functions/pyramid_proposal.py:229: RuntimeWarning: invalid value encountered i$
>  greater_equal
>   keep = np.where((ws >= min_size) & (hs >= min_size))[0]
> Traceback (most recent call last):
>   File "upsnet/upsnet_end2end_train.py", line 426, in <module>
>     upsnet_train()
>   File "upsnet/upsnet_end2end_train.py", line 287, in upsnet_train
>     output = train_model(*batch)
>   File "/home/hxt189898/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in _$
> call__
>     result = self.forward(*input, **kwargs)
>   File "upsnet/../lib/utils/data_parallel.py", line 110, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/hxt189898/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in _$
> call__
>     result = self.forward(*input, **kwargs)
>   File "upsnet/../upsnet/models/resnet_upsnet.py", line 151, in forward
>     rois, _ = self.pyramid_proposal(rpn_cls_prob, rpn_bbox_pred, data['im_info'])
>   File "/home/hxt189898/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in _$
> call__
>     result = self.forward(*input, **kwargs)
>   File "upsnet/../upsnet/operators/modules/pyramid_proposal.py", line 58, in forward
>     bbox_pred[3][[i], :, :, :], bbox_pred[4][[i], :, :, :], torch.from_numpy(im_info[i, :]))
>   File "upsnet/../upsnet/operators/functions/pyramid_proposal.py", line 168, in forward
>     keep = nms(np.hstack((proposals, scores)).astype(np.float32))
>   File "upsnet/../upsnet/nms/nms.py", line 45, in _nms
>     return gpu_nms(dets, thresh, device_id)
>   File "gpu_nms.pyx", line 36, in gpu_nms.gpu_nms
> IndexError: Out of bounds on buffer access (axis 0)

**Comment by YuwenXiong** [comment]
The same as https://github.com/uber-research/UPSNet/issues/36#issuecomment-491589783, otherwise it will cause training failure.

**Comment by JoyHuYY1412** [comment]
> The same as [#36 (comment)](https://github.com/uber-research/UPSNet/issues/36#issuecomment-491589783), otherwise it will cause training failure.

Thanks!
