### ISSUE TITLE
Why your bounding box regression loss is so small?

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#44]
I found that the bounding box regression loss at first of your code is really small, like of ~0.1 scale. Could you give me some explanation?

**Comment by YuwenXiong** [comment]
`bbox_loss` is only for fg rois, and at the beginning when RPN is not well trained there are not many fg rois.

**Comment by JoyHuYY1412** [comment]
> `bbox_loss` is only for fg rois, and at the beginning when RPN is not well trained there are not many fg rois.

So do you mean the loss is calculated among the fg rois but averaged between all the fg and bg rois?

**Comment by YuwenXiong** [comment]
@JoyHuYY1412 yes, see here: https://github.com/uber-research/UPSNet/blob/master/upsnet/models/rcnn.py#L187
