### ISSUE TITLE
Is it OK if I use GCC 4.8.5?

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#46]

**Comment by YuwenXiong** [comment]
No please use gcc 4.9+ since pytorch requires it to build custom operators

**Comment by lfdeep** [comment]
> _No description provided._

Hello，Have you run successfully?

**Comment by JoyHuYY1412** [comment]
> > _No description provided._
> 
> Hello，Have you run successfully?

No, I updated my GCC.
