### ISSUE TITLE
Typo in init_cityscapes.sh?

### ISSUE THREAD

**Issue by WenFuLee** [uber-research/UPSNet#5]
After downloading cityscapes database, I found their file names have no "Train" in 
"cp gtFine/*/*/*labelTrainIds.png labels"

So, I removed "Train" as below
"cp gtFine/*/*/*labelIds.png labels"

Am I right? Thanks.

**Comment by YuwenXiong** [comment]
No, please use https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py to generate labelTrainIds files, use labelIds files is incorrect.
