### ISSUE TITLE
Is your mask_loss the same as MaskRCNN

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#51]
https://github.com/uber-research/UPSNet/blob/ba524d5535e47ea42216dc299fa3effad4e3e661/upsnet/models/rcnn.py#L173
Sorry but I don't understand why you design your loss as this. Why the mask score doesn't need go through sigmoid function?

**Comment by August-en** [comment]
Do you know the reason now? I have the same confusion.
