### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils.colormap'

### ISSUE THREAD

**Issue by liand23** [uber-research/UPSNet#60]
When I run testing and set the vis_mask to be True, the base_dataset.py line 841 
```from lib.utils.colormap import colormap```
is calling for colormap, which is not found. Is it something is missing in the util folder?

**Comment by lfdeep** [comment]
I meet the same problems!

**Comment by YuwenXiong** [comment]
the `colormap.py` file is added
