### ISSUE TITLE
Help: about the dataset(from a rookie)

### ISSUE THREAD

**Issue by AugustYuan** [uber-research/UPSNet#64]
I find that the paths 'lib/dataset_devkit/panopticapi/panoptic_coco_categories.json' and 'data/coco/annotations/panoptic_coco_categories_stff.json' are used in init_coco.py, but the folder 'lib/dataset_devkit' is empty. And I can't the two files in coco panoptic annotation folder. So where should I get the two files. If anybody knows, please give me a hand. Thanks a lot.

**Comment by AugustYuan** [comment]
Oh, Im sorry, I get it.

**Comment by SwayKing** [comment]
Could you please share your solution? I cannot find the file 'data/coco/annotations/panoptic_coco_categories_stff.json'

**Comment by StoicGilgamesh** [comment]
Hey AugustYuan! how did you solved the problem? I am facing the same issue.

**Comment by SunNYNO1** [comment]
i meet the same problem, could you help me?
