### ISSUE TITLE
Help: segmentation fault

### ISSUE THREAD

**Issue by AugustYuan** [uber-research/UPSNet#66]
When the program runs to "output=train_model(*batch)" in upsnet_end2end_train.py file, i will print "segmentation fault" with no other error imformation. I have checked my gcc version and pytorch version are 7.2.0 and 0.4.1, is there any solution? Thanks a lot!

**Comment by QuarK30** [comment]
Have you found solution for this issue?

**Comment by charlotte12l** [comment]
Have you found solution for this issue? I encountered the same problem :( Thanks!

**Comment by masonwang96** [comment]
same problem...to be solved...

**Comment by AugustYuan** [comment]
> When the program runs to "output=train_model(*batch)" in upsnet_end2end_train.py file, i will print "segmentation fault" with no other error imformation. I have checked my gcc version and pytorch version are 7.2.0 and 0.4.1, is there any solution? Thanks a lot!
