### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by gaussiangit** [uber-research/UPSNet#69]
I trained coco for more than 160000 iterations, still get PQ around 35 with given config. Training for longer does help a bit but I see that your pretrained weights achieved results with 98000 iterations.
Do you know what could be wrong ?

**Comment by YuwenXiong** [comment]
If you only use 4 gpus (i.e batch size =4) the expected #iter is 360k or longer, the 90k one is trained with 16gpus

**Comment by gaussiangit** [comment]
Got it. Thank you :)
