### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by gaussiangit** [uber-research/UPSNet#72]
As mentioned in the paper inference time on single image of COCO dataset is 171 ms.
Does that mean you get around 5.8 FPS for any image ? 
When I ran your evaluation script on 4 GPU strictly on coco val2017, net_time is different every time I run the script. Sometimes it takes more than mins for particular batches. 
Can you share your thoughts on this ? @YuwenXiong

**Comment by YuwenXiong** [comment]
We found the time is not accurate with #GPU > 1 or #worker of dataloader > 0.

So please try again with the settings above.

Also please check whether your environment/hardware is setup correctly. Minutes for a image is absolutely abnormal.

**Comment by lfdeep** [comment]
@gaussiangit  Excuse me, how long it takes you to train a model. What is the number of GPUs?

**Comment by discretecoder** [comment]
How does the inference work? is there a script for inference
