### ISSUE TITLE
Regarding Category Id assignment in init_coco.py

### ISSUE THREAD

**Issue by ShreyPaharia** [uber-research/UPSNet#73]
While assignment of categories, you start with 0 and then assign these the category ids to the instances to create semantic data. Penoptic images contain 0 pixel values to signify unknown pixel. Thus in semantic data there is category id 0 in every image which corresponds to banner.Could someone tell me where and how is this being handled?

**Comment by YuwenXiong** [comment]
Similar issue has been raised in https://github.com/uber-research/UPSNet/issues/55, and it has been fixed in the latest code, see https://github.com/uber-research/UPSNet/blob/master/init_coco.sh#L3. We will change unknown from 0 to 255 during semantic segmentation ground truth generation.
