### ISSUE TITLE
upsnet/models/fcn.py has a conv layer definition with parameter in_channels given twice.   

### ISSUE THREAD

**Issue by feedforward** [uber-research/UPSNet#78]
Hi, for the deform-conv def in fcn.py, parameter for both number of input channels and number of output channels is same. (in_channels)   
Is this choice deliberate? can you please explain why.

Location - Line 52
https://github.com/uber-research/UPSNet/blob/master/upsnet/models/fcn.py

Thanks

**Comment by YuwenXiong** [comment]
We only use out_channel for the last conv layer in this subnet, so yes it is.

**Comment by feedforward** [comment]
I see, Thanks.
