### ISSUE TITLE
Training is slow.

### ISSUE THREAD

**Issue by dxbdxx** [uber-research/UPSNet#8]
Hello, I am trying to reproduce the results without horovod.
I use 4 Tesla K80 gpus (12GB) and train the net with "upsnet_resnet50_coco_4gpu.yaml" but I find that it may take more than 10 days for training.
Have you got some advice for speeding up the training?
Thanks.

**Comment by YuwenXiong** [comment]
K80 is ~2x slower than 1080 Ti (5.6 TFLOPS vs 11.3 TFLOPS). And we suggest use 8-16 GPUs for coco experiments. I think on COCO 10 days for 4 K80 GPU is a normal time. Please try smaller dataset such as Cityscapes.

**Comment by dxbdxx** [comment]
Thank you. I'll try this.

**Comment by lxtGH** [comment]
@YuwenXiong Hi, What using 4 1080TI  GPU on COCO?  How long does it cost on COCO? I have tried to train cityscapes which cost me about 2 days.

**Comment by YuwenXiong** [comment]
4 1080Ti for cityscapes should be done < 1day, and for coco it will be ~5 days
