### ISSUE TITLE
can't run on Mapillary vistas dataset

### ISSUE THREAD

**Issue by yangia** [uber-research/UPSNet#81]
I tried to train the model on Mapillary vistas dataset. However, after days' effort, I still can't make it.
Here is what I've done:
1. convert the Mapillary `panoptic_2018.json` to `panoptic_2018_stff.json` via `init_coco.py` with some minor changes.
2. generate semantic gt via `panoptic2semantic_segmentation.py` as it is done in `init_coco.sh`
3. generate `instances_2018_stff.json` from `panoptic_2018_stff.json` via `panoptic2detection_coco_format.py` with some changes. of course `--things-only` is set.
4. train upsnet with similar configuration as `upsnet_resnet50_coco_4gpu.yaml`.
5. after fixing some bugs of the compatibility of annotation formats, it still cannot run. the feedback is like this
![upsnet](https://user-images.githubusercontent.com/34333375/62822676-4dcaf000-bbb9-11e9-8629-152c7f3a91ff.PNG)
some trials:
1. I applied the above 1-5 to COCO `panoptic_{train/val}2017.json`. The upsnet run smoothly.
2. Since the bug appears at `proposal_mask_target.py` as it is shown in the above image, I tried to filter some small instance regions (area < 25), but in vain.
could anyone give some suggestions? thanks in advance.

**Comment by yangia** [comment]
solved. a tiny mistake. background was ignored in `num_classes`.

**Comment by discretecoder** [comment]
could you share your code here? @yangia

**Comment by discretecoder** [comment]
hi @yangia how did you use vistas ? did you convert it to coco? was it enough just to create coco json format files

**Comment by Jinming-Su** [comment]
@yangia Would you share the performance trained on Mapillary vistas dataset?
