### ISSUE TITLE
training on my dataset other than coco and cityscapes

### ISSUE THREAD

**Issue by shubhaminnani** [uber-research/UPSNet#82]
@YuwenXiong I want to load my dataset with annotation and images already in png format how to load and where to load it. Is there any need to change init_coco.py? Thanks in Advance

**Comment by kahnchana** [comment]
You could convert it to the coco or cityscapes format and run the training like that.

**Comment by shubhaminnani** [comment]
how can I convert images to json file? @kahnchana

**Comment by kahnchana** [comment]
http://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch
This was useful for me
