### ISSUE TITLE
GPU allocation

### ISSUE THREAD

**Issue by discretecoder** [uber-research/UPSNet#89]
I have 8 GPUs available and I wish to train on the GPUs 3,4,5,6, when i change the gpus to '3,4,5,6' and also the same for CUDA devices, I get an error from train_model = eval(config.symbol)().cuda() in the training script. it looks like it still uses gpus 0,1,2,3 for this step. what would be a solution? Thank you

**Comment by YuwenXiong** [comment]
Just set `CUDA_VISIBLE_DEVICES=3,4,5,6` and leave the config files unchanged.
