### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by renxuezi** [uber-research/UPSNet#93]
How to remove all multi-thread code and use a single core in base_dataset.py？
I have changed "annotations.extend(p[0]);pan_all.extend(p[1])"  into  "pan_all.extend(p)",
now it got stuck when the results were output，how should I modify code?

**Comment by YuwenXiong** [comment]
You can set `cpu_num` variable in `base_dataset.py` to 1 to avoid memory issue.

**Comment by renxuezi** [comment]
Thank you for your reply,my problem solved after I've changed to a better GPU.
