### ISSUE TITLE
Question about the unknown class in evaluation

### ISSUE THREAD

**Issue by Jacobew** [uber-research/UPSNet#95]
Hi, thanks for the excellent work!  @YuwenXiong 

I have a question about the evaluation of UPSNet. The paper says, " In evaluating the metric, any pixel belonging to unknown is ignored, i.e., setting to void which will not contribute to the results".
Does it mean you have modified panoptic ground truth images and do not take the sampled unknown segments into consideration? 

BTW, is there any result of UPSNet without deformable convolution on COCO val set? This was not given in the ablation studies section. 

Many thanks! Looking forward to your reply!

**Comment by YuwenXiong** [comment]
The ground truth images are not modified, ignoring unknown/void pixels is by design (https://github.com/cocodataset/panopticapi/blob/master/panopticapi/evaluation.py#L132).
Unfortunately there is no non-deformconv version for our model, you can modify the model definition and run it by yourself.
